### ISSUE TITLE
Not asynchronous https get and post request

### ISSUE THREAD

**Issue by patcmorneau** [CIDCO-dev/Poseidon#393] opened 2024-09-10 13:48 UTC
When the application makes a GET request it will block until either:

1. The server responds within 60 seconds.
2. A timeout occurs after 60 seconds, resulting in an error.

This can indeed make the application unresponsive during this period, as it has been observed.

**Comment by glabmoris** [comment] 2024-10-21 17:30
Duplicate of #387

**Closed by glabmoris** 2024-10-21 17:30 UTC
